Friendly npc
CryptoCreations/LitiGame pull request #20
Opened 2021-01-29 16:41 UTC by alcoholicwaluigi

NPC + NPC interactions

2021-01-29 17:57 UTC, T0m2223 commented on src/de/litigame/entities/Player.java
> +@EntityInfo(width = 16, height = 16)
Warum?

2021-01-29 17:58 UTC, alcoholicwaluigi commented on src/de/litigame/entities/Player.java
> +@EntityInfo(width = 16, height = 16)
die sprite ist 16x16 ich denke 6 war ein fehler

2021-01-29 18:07 UTC, T0m2223 requested changes
Ich kann die Struktur in NpcController.update() noch nicht sehen... Mach dir nochmal klar wie sich das NPC verhalten soll.

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/Player.java
> +@EntityInfo(width = 16, height = 16)
Die player sprite sollte noch 16x6 sein, glaub ich

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/Player.java
> +	public void interactNPC() {
braucht keine eigene methode, sollte einfach interact() sein

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/Player.java
> +	public ArrayList<NpcController> interactListener;
Set ist besser als List (performance)

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/NPC.java
> +    public double distanceTo(Entity other) {
was bringt diese methode?

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/NPC.java
> +    public boolean touches(Rectangle2D rect) {
was bringt diese methode?

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/NPC.java
> +    public void update() {}
was bringt diese methode?

2021-01-29 18:07 UTC, T0m2223 commented on src/de/litigame/entities/NpcController.java
> +    private void turnToTarget() {
wozu braucht man diese methode?

2021-01-29 18:09 UTC, alcoholicwaluigi commented on src/de/litigame/entities/Player.java
> +	public void interactNPC() {
player hat schon interact()
interactNPC() wird in Interact aufgerugen

2021-01-29 18:11 UTC, alcoholicwaluigi commented on src/de/litigame/entities/NPC.java
> +    public void update() {}
NPC extendet IUpdatable, was NPC braucht um `Game.loop().attach(this);` auszuführen

2021-01-29 18:12 UTC, alcoholicwaluigi commented on src/de/litigame/entities/NpcController.java
> +    private void turnToTarget() {
Der NPC guckt den player an

2021-01-29 18:16 UTC, T0m2223 commented on src/de/litigame/entities/NPC.java
> +    public void update() {}
Wieso soll der NPC an der Gameloop hängen? Wir haben doch schon einen Controller für den NPC, der das movement übernimmt. Also wofür?

2021-01-29 18:19 UTC, alcoholicwaluigi commented on src/de/litigame/entities/Player.java
> +	public ArrayList<NpcController> interactListener;
Ich habe es nicht geschafft ein Set zu iterieren kannst du aber gerne machen

2021-02-01 13:45 UTC, T0m2223 approved these changes

2021-02-01 13:48 UTC, merged